// <auto-generated />
using System;
using EstagioCheck.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstagioCheck.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507011153_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstagioCheck.API.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("aluno");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivitiesDescription")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("IrregularityReason")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("pendente");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ValidatedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.HasIndex("ValidatedById");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("ActivitiesScore")
                        .HasColumnType("smallint");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<short>("PlanningScore")
                        .HasColumnType("smallint");

                    b.Property<short>("PostureScore")
                        .HasColumnType("smallint");

                    b.Property<Guid>("PreceptorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PreceptorId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.FormativeFollowup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AspectosAprimorar")
                        .HasColumnType("text");

                    b.Property<string>("ComunicacaoEquipe")
                        .HasColumnType("text");

                    b.Property<string>("ComunicacaoEscuta")
                        .HasColumnType("text");

                    b.Property<string>("ComunicacaoPaciente")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EvolucaoSemanal")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("FollowUpEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FollowUpStart")
                        .HasColumnType("date");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservacoesDocente")
                        .HasColumnType("text");

                    b.Property<string>("OrganizacaoPlanejamento")
                        .HasColumnType("text");

                    b.Property<string>("OrganizacaoRegistros")
                        .HasColumnType("text");

                    b.Property<string>("OrganizacaoSeguranca")
                        .HasColumnType("text");

                    b.Property<string>("ParticipacaoAprendizado")
                        .HasColumnType("text");

                    b.Property<string>("ParticipacaoAutocritica")
                        .HasColumnType("text");

                    b.Property<string>("ParticipacaoIniciativa")
                        .HasColumnType("text");

                    b.Property<string>("PeriodLabel")
                        .HasColumnType("text");

                    b.Property<string>("PosturaEtica")
                        .HasColumnType("text");

                    b.Property<string>("PosturaPontualidade")
                        .HasColumnType("text");

                    b.Property<string>("PosturaResponsabilidade")
                        .HasColumnType("text");

                    b.Property<string>("Potencialidades")
                        .HasColumnType("text");

                    b.Property<Guid>("PreceptorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PreceptorSignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PreceptorSignedIp")
                        .HasColumnType("text");

                    b.Property<string>("PreceptorSignedName")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreceptorSignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Semester")
                        .HasColumnType("text");

                    b.Property<string>("Shift")
                        .HasColumnType("text");

                    b.Property<string>("SituacoesRelevantes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("rascunho");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StudentSignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StudentSignedIp")
                        .HasColumnType("text");

                    b.Property<string>("StudentSignedName")
                        .HasColumnType("text");

                    b.Property<Guid?>("StudentSignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PreceptorId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("FormativeFollowups");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("GroupMemberships");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsInstitution")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer");

                    b.Property<string>("ShiftEnd")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ShiftStart")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.RotationSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("PreceptorId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredHours")
                        .HasColumnType("integer");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PreceptorId");

                    b.ToTable("RotationSchedules");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("EstagioCheck.API.Models.Location", "Location")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.RotationSchedule", "Schedule")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "ValidatedBy")
                        .WithMany()
                        .HasForeignKey("ValidatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Location");

                    b.Navigation("Schedule");

                    b.Navigation("Student");

                    b.Navigation("ValidatedBy");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.Evaluation", b =>
                {
                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Preceptor")
                        .WithMany("EvaluationsAsPreceptor")
                        .HasForeignKey("PreceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.RotationSchedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Student")
                        .WithMany("EvaluationsAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preceptor");

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.FormativeFollowup", b =>
                {
                    b.HasOne("EstagioCheck.API.Models.StudentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Preceptor")
                        .WithMany("FollowupsAsPreceptor")
                        .HasForeignKey("PreceptorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.RotationSchedule", "Schedule")
                        .WithMany("Followups")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Student")
                        .WithMany("FollowupsAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Location");

                    b.Navigation("Preceptor");

                    b.Navigation("Schedule");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.GroupMembership", b =>
                {
                    b.HasOne("EstagioCheck.API.Models.StudentGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Student")
                        .WithOne("GroupMembership")
                        .HasForeignKey("EstagioCheck.API.Models.GroupMembership", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.RotationSchedule", b =>
                {
                    b.HasOne("EstagioCheck.API.Models.StudentGroup", "Group")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.Location", "Location")
                        .WithMany("Schedules")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EstagioCheck.API.Models.ApplicationUser", "Preceptor")
                        .WithMany("SchedulesAsPreceptor")
                        .HasForeignKey("PreceptorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("Location");

                    b.Navigation("Preceptor");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.ApplicationUser", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EvaluationsAsPreceptor");

                    b.Navigation("EvaluationsAsStudent");

                    b.Navigation("FollowupsAsPreceptor");

                    b.Navigation("FollowupsAsStudent");

                    b.Navigation("GroupMembership");

                    b.Navigation("SchedulesAsPreceptor");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.Location", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.RotationSchedule", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Followups");
                });

            modelBuilder.Entity("EstagioCheck.API.Models.StudentGroup", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
